version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: opentcfca-nginx